'use client';

import Head from "next/head";

import { ThemeProvider } from "styled-components"

import { GlobalStyle } from '@/globalStyle'

import { theme } from "@/constants/colors";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

console.log(theme)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <ThemeProvider theme={theme}>
          <GlobalStyle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
