'use client';

import { ThemeProvider } from "styled-components"

import { GlobalStyle } from '@/globalStyle'
// import './globals.css'
import { Inter } from 'next/font/google'

import { theme } from "@/constants/colors";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

console.log(theme)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <GlobalStyle />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
